---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: 44.203.78.125
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup